export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
  
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';
export const GET_BORROWER = 'GET_BORROWER';
export const GET_BORROWER_SUCCESS = 'GET_BORROWER_SUCCESS';
export const GET_BORROWER_ERROR = 'GET_BORROWER_ERROR';

export const GET_SUMMARY = 'GET_SUMMARY';
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS';
export const GET_SUMMARY_ERROR = 'GET_SUMMARY_ERROR';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';
export const GET_ACTIVITIES_ERROR = 'GET_ACTIVITIES_ERROR';

export const GET_STATEMENTS = 'GET_STATEMENTS';
export const GET_STATEMENTS_SUCCESS = 'GET_STATEMENTS_SUCCESS';
export const GET_STATEMENTS_ERROR = 'GET_STATEMENTS_ERROR';
export const GET_RELATIONSHIP = 'GET_RELATIONSHIP';
export const GET_RELATIONSHIP_SUCCESS = 'GET_RELATIONSHIP_SUCCESS';
export const GET_RELATIONSHIP_ERROR = 'GET_RELATIONSHIP_ERROR';
export const GET_CHECKLIST = 'GET_CHECKLIST';
export const GET_CHECKLIST_SUCCESS = 'GET_CHECKLIST_SUCCESS';
export const GET_CHECKLIST_ERROR = 'GET_CHECKLIST_ERROR';
export const POST_DOCUMENT = 'POST_DOCUMENT';
export const POST_DOCUMENT_SUCCESS = 'POST_DOCUMENT_SUCCESS';
export const POST_DOCUMENT_ERROR = 'POST_DOCUMENT_ERROR';
export const GET_ADDITIONAL_DOCUMENT = 'GET_ADDITIONAL_DOCUMENT';
export const GET_ADDITIONAL_DOCUMENT_SUCCESS = 'GET_ADDITIONAL_DOCUMENT_SUCCESS';
export const GET_ADDITIONAL_DOCUMENT_ERROR = 'GET_ADDITIONAL_DOCUMENT_ERROR';
export const GET_USERMESSAGE = 'GET_USERMESSAGE';
export const GET_USERMESSAGE_SUCCESS = 'GET_USERMESSAGE_SUCCESS';
export const GET_USERMESSAGE_ERROR = 'GET_USERMESSAGE_ERROR';
export const SAVE_ADDITIONAL_DOCUMENT = 'SAVE_ADDITIONAL_DOCUMENT';
export const SAVE_ADDITIONAL_DOCUMENT_SUCCESS = 'SAVE_ADDITIONAL_DOCUMENT_SUCCESS';
export const SAVE_ADDITIONAL_DOCUMENT_ERROR = 'SAVE_ADDITIONAL_DOCUMENT_ERROR';
export const SAVE_SEND_MESSAGE = 'SAVE_SEND_MESSAGE';
export const SAVE_SEND_MESSAGE_SUCCESS = 'SAVE_SEND_MESSAGE_SUCCESS';
export const SAVE_SEND_MESSAGE_ERROR = 'SAVE_SEND_MESSAGE_ERROR';
 
export const GET_RISK = 'GET_RISK';
export const GET_RISK_SUCCESS = 'GET_RISK_SUCCESS';
export const GET_RISK_ERROR = 'GET_RISK_ERROR';
 

export const LOG_OUT = 'LOG_OUT';